### ISSUE TITLE
Utility functions for gptai-turbo

### ISSUE THREAD

**Issue by fanselau** [antonhibl/gptai#2]
Hi, I guess this is not really even an issue, but more of a feature request. Will you provide the utility functions that you have for the gpt-4 / gpt-3.5-turbo requests as well (maybe even just something like having a "proxy" function in between where you could exchange gptai-send-query with gptai-turbo-query under the hood)? 

Really cool library btw^^ Would love to see something build like those brushes in copilot labs in vs code

**Comment by antonhibl** [comment]
@lucafanselau I see what you mean, so have some of the code tooling functionalities allow for gpt-3.5 and 4? I don't think it would be too much trouble, if possible I would like to do this without duplicating code unneccessarily so maybe the easiest way is to have gptai-send-request, dispatch to 3.5-turbo or gpt-4 if the user specifies that. I will look into it!

**Comment by antonhibl** [comment]
this should be mostly possible by just configuring the gptai-model variable as of the latest updates. There may be some inconsistency with it since the models do have slightly different accepted formats for their queries.
